version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    environment:
      - APP_ROLE=frontend
      - PMA_HOST=db

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8889:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    environment:
      - APP_ROLE=backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service_center
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"  
    environment:
      PMA_HOST: db 
    depends_on:
      - db

volumes:
  mysql_data: